name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build macOS version
      run: swift build --verbose
    - name: Build iOS version
      run: xcodebuild -scheme StringBooster -destination 'platform=iOS Simulator,id=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder,name=Any iOS Simulator Device'
    - name: Build watchOS version
      run: xcodebuild -scheme StringBooster -destination 'platform=watchOS Simulator,name=Any watchOS Simulator Device'
    - name: Build tvOS version
      run: xcodebuild -scheme StringBooster -destination 'platform=tvOS Simulator,name=Any tvOS Simulator Device'
    - name: Run tests
      run: swift test --verbose
