name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build macOS version
      run: swift build --verbose
    - name: Build iOS version
      run: xcodebuild -scheme StringBooster -destination 'platform=iOS Simulator,name=iPhone 14'
    - name: Build watchOS version
      run: xcodebuild -scheme StringBooster -destination 'platform=watchOS Simulator,name=Apple Watch Series 8 (41mm)'
    - name: Build tvOS version
      run: xcodebuild -scheme StringBooster -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)'
    - name: Run tests
      run: swift test --verbose
