name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build macOS version
      run: swift build --verbose
    - name: Build iOS version
      run: xcodebuild -scheme StringBooster -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 8'
    - name: Run tests
      run: swift test --verbose
