name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build macOS version
      run: swift build --verbose --sdk macos
    - name: Run tests for macOS version
      run: swift test --verbose --sdk macos
    - name: Build iOS version
      run: swift build --verbose --sdk ios
    - name: Run tests for iOS version
      run: swift test --verbose --sdk ios
